### ISSUE TITLE
Shop 화면 구성

### ISSUE THREAD

**Issue by kumann2** [ProjectInTheClass/ForYou#10]
Shop 화면 상품 리스트, Segment, Table 생성

1. 상품리스트를 기반으로 외투, 상의, 하의, 신발, 기타 분류.
2. Segment Controller 만들어서 작동.
3. View Controller 내부에 Table 생성하여 Load.

**Comment by iAmJunha** [comment]
ShopViewController error 수정을 위해 reopen

**Comment by iAmJunha** [comment]
ShopViewController 클래스 내,
SegmentControl 을 위한 filter함수를 수정하고
shopScene  구성완료함
