### ISSUE TITLE
Cloth List 만들기

### ISSUE THREAD

**Issue by kumann2** [ProjectInTheClass/ForYou#2]
Cloth 항목
: 브랜드(String), 모델명(String), 가격(Int), 상세이미지(Array), 항목코드(Int), 스타일코드(Int), 색상코드(Int)

 스타일코드, 색상코드는 취향분석에서 Array만들어서 넣을 때 사용될 예정.

**Comment by iAmJunha** [comment]
cloth List에 각 코드가 포함된 clothData set추가함
